### PR TITLE
increase swim-js version to support nat/docker

### PR DESCRIPTION
**Pull request by AdrianRossouw**
Need a new version to support this : https://github.com/mrhooray/swim-js/pull/5

which will allow us to containerize seneca-mesh services.

@rjrodger this is kind of urgent / a blocker.

### CODE REVIEW

**Comment by AdrianRossouw** [comment]
tests failed due to msgpack compilation issue.
i don't have the permissions to retry them.

**Comment by AdrianRossouw** [comment]
@rjrodger ping?

**Comment by rjrodger** [comment]
what --net=host workaround?

**Comment by mcollina** [comment]
Even with --net=host swim-js will not work on docker. You need this fix.

**Pull request merged**
